### PR TITLE
Added Linux alternative

### PR DESCRIPTION
**Pull request by ItsLeon15**
I haven't tested this on Windows so it may or may not work.

### CODE REVIEW

**Comment by Bonnie39** [comment]
This seems to work running under a Linux virtual machine. However it is not printing the final message when it comes across a valid password (using a test .7z file where the password is 0000000000000024). I'm not quite sure how to fix this but I suspect it has something to do with changing text color working differently on Linux. This is good enough for now though.

**Comment by ItsLeon15** [comment]
> This seems to work running under a Linux virtual machine. However it is not printing the final message when it comes across a valid password (using a test .7z file where the password is 0000000000000024). I'm not quite sure how to fix this but I suspect it has something to do with changing text color working differently on Linux. This is good enough for now though.

Does the program stop or give any indication that it's found the password. If it doesn't do anything and keeps running then it's a bit useless. I'll try and see why that is happening.

**Comment by Bonnie39** [comment]
> Does the program stop or give any indication that it's found the password.

The program stops trying combinations upon finding the correct password, but doesn't fully quit and waits for the user to press CTRL + C. It also doesn't indicate which combination was the correct one. Running with only 1 thread, this isn't really much of an issue because you can assume it was just the last code tried. However with multiple threads they may print out of sync (the same goes for my original Windows version).

**Comment by ItsLeon15** [comment]
> > Does the program stop or give any indication that it's found the password.
> 
> The program stops trying combinations upon finding the correct password, but doesn't fully quit and waits for the user to press CTRL + C. It also doesn't indicate which combination was the correct one. Running with only 1 thread, this isn't really much of an issue because you can assume it was just the last code tried. However with multiple threads they may print out of sync (the same goes for my original Windows version).

A solution might be to put all combinations into an **unordered_set** but I'll look into the multi threading as that might not 100% work. Would it be possible to add me on Discord just so it is a bit easier to see if there is an issue or to improve anything? My username is Leon1273.

**Pull request merged**
